import type { FamilyWalletsData } from '@/types/family';

export const familyWalletsDemoData: FamilyWalletsData = {
  family: {
    memberCount: 3,
    name: 'Rahman Family',
  },
  members: [
    { id: 'ayesha', initials: 'AR', name: 'Ayesha Rahman', role: 'owner' },
    { id: 'tanvir', initials: 'TR', name: 'Tanvir Rahman', role: 'editor' },
    { id: 'nabila', initials: 'NR', name: 'Nabila Rahman', role: 'editor' },
  ],
  wallets: [
    {
      accessedBy: ['ayesha', 'tanvir', 'nabila'],
      balance: 265_000,
      currency: 'BDT',
      id: 'brac-family',
      isDefault: true,
      monthlyExpense: 25_800,
      monthlyIncome: 120_000,
      name: 'BRAC Family Account',
      transactions: 11,
      type: 'bank',
      updated: 'Updated today',
    },
    {
      accessedBy: ['ayesha', 'tanvir', 'nabila'],
      balance: 38_600,
      currency: 'BDT',
      id: 'household-cash',
      isDefault: false,
      monthlyExpense: 11_650,
      monthlyIncome: 5_000,
      name: 'Household Cash',
      transactions: 5,
      type: 'cash',
      updated: 'Updated yesterday',
    },
    {
      accessedBy: ['ayesha', 'tanvir'],
      balance: 21_250,
      currency: 'BDT',
      id: 'bkash-household',
      isDefault: false,
      monthlyExpense: 4_850,
      monthlyIncome: 3_500,
      name: 'bKash Household',
      transactions: 2,
      type: 'mobile',
      updated: 'Updated 2 days ago',
    },
  ],
  activities: [
    {
      amount: 2_450,
      date: '30 Jul, 2026',
      id: 'activity-1',
      note: 'Weekly grocery run',
      paidBy: 'ayesha',
      splitLabel: 'Split equally',
      title: 'Grocery shopping',
      type: 'expense',
      walletId: 'household-cash',
    },
    {
      amount: 1_840,
      date: '29 Jul, 2026',
      id: 'activity-2',
      note: 'July electricity bill',
      paidBy: 'tanvir',
      splitLabel: 'Split equally',
      title: 'Electricity bill',
      type: 'expense',
      walletId: 'bkash-household',
    },
    {
      amount: 8_500,
      date: '28 Jul, 2026',
      id: 'activity-3',
      note: 'Monthly family contribution',
      paidBy: 'nabila',
      splitLabel: 'Contribution',
      title: 'Wallet contribution',
      type: 'income',
      walletId: 'brac-family',
    },
    {
      amount: 5_000,
      date: '27 Jul, 2026',
      id: 'activity-4',
      note: 'Cash for household costs',
      paidBy: 'ayesha',
      splitLabel: 'Not split',
      title: 'Wallet transfer',
      type: 'transfer',
      walletId: 'brac-family',
    },
  ],
};
