'use client'

import type { FormEvent, ReactNode } from 'react'
import { Check, Ellipsis, FileSpreadsheet, Pencil, ReceiptText, Trash2, Upload, X } from 'lucide-react'
import { useState } from 'react'

import { buttonVariants } from '@/components/ui/button'
import { cn } from '@/lib/utils'

export type FinanceDialogKind = 'transaction' | 'import' | 'export' | 'budget' | 'goal' | 'contribution'

const input = 'h-10 w-full rounded-md border border-input bg-card px-3 text-sm text-foreground outline-none placeholder:text-muted-foreground focus:border-primary focus:ring-3 focus:ring-primary/15'
const select = 'h-10 w-full rounded-md border border-input bg-card px-3 text-sm text-foreground outline-none focus:border-primary focus:ring-3 focus:ring-primary/15'

export function FinanceDialog({ kind, onClose, editing = false }: { kind: FinanceDialogKind; onClose: () => void; editing?: boolean }) {
  const [saved, setSaved] = useState(false)
  const title = editing ? `Edit ${kind === 'transaction' ? 'transaction' : kind === 'budget' ? 'budget' : 'savings goal'}` : { transaction: 'Add transaction', import: 'Import transactions', export: 'Export transactions', budget: 'Add budget', goal: 'New savings goal', contribution: 'Add contribution' }[kind]
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaved(true) }
  return <div aria-modal="true" className="fixed inset-0 z-60 grid place-items-end bg-foreground/40 p-0 backdrop-blur-[1px] sm:place-items-center sm:p-4" role="dialog"><section className="w-full max-w-lg rounded-t-xl border border-border bg-card shadow-xl sm:rounded-xl"><header className="flex items-center justify-between border-b border-border px-5 py-4"><h2 className="font-semibold">{title}</h2><button aria-label="Close dialog" className={buttonVariants({ variant: 'ghost', size: 'icon-xs' })} onClick={onClose} type="button"><X /></button></header><form className="max-h-[65vh] space-y-4 overflow-y-auto p-5" id="finance-dialog-form" onSubmit={submit}>{saved ? <Success kind={kind} /> : <Fields kind={kind} />}</form><footer className="flex items-center justify-end gap-2 border-t border-border bg-muted/25 px-5 py-4">{saved ? <button className={buttonVariants()} onClick={onClose} type="button"><Check data-icon="inline-start" />Done</button> : <><button className={buttonVariants({ variant: 'ghost' })} onClick={onClose} type="button">Cancel</button><button className={buttonVariants()} form="finance-dialog-form" type="submit">{kind === 'export' ? 'Export CSV' : kind === 'import' ? 'Import file' : kind === 'contribution' ? 'Add contribution' : editing ? 'Save changes' : 'Save'}</button></>}</footer></section></div>
}

function Label({ title, children }: { title: string; children: ReactNode }) { return <label className="block space-y-1.5"><span className="text-sm font-medium">{title}</span>{children}</label> }
function Switch({ defaultChecked = false, label, detail }: { defaultChecked?: boolean; label: string; detail?: string }) { return <label className="flex cursor-pointer items-start justify-between gap-4 rounded-lg border border-border p-3"><span><span className="block text-sm font-medium">{label}</span>{detail ? <span className="mt-0.5 block text-xs text-muted-foreground">{detail}</span> : null}</span><span className="relative mt-0.5 inline-flex shrink-0"><input className="peer sr-only" defaultChecked={defaultChecked} type="checkbox" /><span className="h-5 w-9 rounded-full bg-muted transition-colors peer-checked:bg-primary" /><span className="absolute left-0.5 top-0.5 size-4 rounded-full bg-card shadow-xs transition-transform peer-checked:translate-x-4" /></span></label> }
function Fields({ kind }: { kind: FinanceDialogKind }) {
  const [type, setType] = useState<'income' | 'expense'>('expense')
  const [fileName, setFileName] = useState('')
  if (kind === 'import') return <><p className="text-sm text-muted-foreground">Upload a CSV file to add multiple transactions. You will get a validation preview before import.</p><label className="grid min-h-40 cursor-pointer place-items-center rounded-lg border border-dashed border-primary/35 bg-primary/5 p-6 text-center"><input accept=".csv,text/csv" className="sr-only" onChange={(event) => setFileName(event.target.files?.[0]?.name ?? '')} type="file" /><div><FileSpreadsheet className="mx-auto mb-3 size-8 text-primary" /><p className="text-sm font-medium">{fileName || 'Choose or drop a CSV file'}</p><p className="mt-1 text-xs text-muted-foreground">Maximum file size: 1 MB</p></div></label><p className="text-xs text-muted-foreground">Required: date, description, amount, type, category and wallet.</p></>
  if (kind === 'export') return <><p className="text-sm text-muted-foreground">Choose the transactions and fields to include in your CSV export.</p><Label title="Date range"><select className={select}><option>July 2026</option><option>Last 3 months</option><option>This year</option><option>All time</option></select></Label><Switch defaultChecked detail="Add notes and wallet details to each row." label="Include additional details" /></>
  if (kind === 'transaction') return <><Label title="Type"><div className="grid grid-cols-2 rounded-md bg-muted p-1"><button className={cn('rounded-sm px-3 py-2 text-sm font-medium', type === 'income' ? 'bg-card text-success shadow-xs' : 'text-muted-foreground')} onClick={() => setType('income')} type="button">Income</button><button className={cn('rounded-sm px-3 py-2 text-sm font-medium', type === 'expense' ? 'bg-card text-danger shadow-xs' : 'text-muted-foreground')} onClick={() => setType('expense')} type="button">Expense</button></div></Label><Label title="Description"><input className={input} placeholder="e.g. Grocery shopping" required /></Label><div className="grid gap-4 sm:grid-cols-2"><Label title="Amount"><input className={input} min="1" placeholder="0" required type="number" /></Label><Label title="Date"><input className={input} defaultValue="2026-07-28" required type="date" /></Label></div><div className="grid gap-4 sm:grid-cols-2"><Label title="Category"><select className={select}><option>{type === 'income' ? 'Salary' : 'Food'}</option><option>{type === 'income' ? 'Freelance' : 'Transport'}</option><option>{type === 'income' ? 'Other income' : 'Bills'}</option></select></Label><Label title="Wallet"><select className={select}><option>Cash</option><option>BRAC Bank</option><option>bKash</option></select></Label></div><Label title="Note (optional)"><input className={input} placeholder="Add a note" /></Label><label className="flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-dashed border-border bg-muted/35 p-3 text-center text-xs text-muted-foreground"><input accept="image/png,image/jpeg,application/pdf" className="sr-only" onChange={(event) => setFileName(event.target.files?.[0]?.name ?? '')} type="file" /><Upload className="size-4 text-primary" />{fileName || 'Attach receipt (JPG, PNG or PDF)'}</label></>
  if (kind === 'budget') return <><Label title="Category"><select className={select}><option>Food & dining</option><option>Transport</option><option>Shopping</option><option>Entertainment</option><option>Health</option></select></Label><div className="grid gap-4 sm:grid-cols-2"><Label title="Monthly limit"><input className={input} min="1" placeholder="0" required type="number" /></Label><Label title="Alert threshold"><select className={select}><option>80%</option><option>90%</option></select></Label></div><Label title="Period"><select className={select}><option>Monthly</option><option>Yearly</option></select></Label><Switch detail="Add unused funds to the next month." label="Roll over unspent amount" /></>
  if (kind === 'goal') return <><Label title="Goal name"><input className={input} placeholder="e.g. Emergency fund" required /></Label><div className="grid gap-4 sm:grid-cols-2"><Label title="Target amount"><input className={input} min="1" placeholder="0" required type="number" /></Label><Label title="Already saved"><input className={input} min="0" placeholder="0" type="number" /></Label></div><Label title="Target deadline"><input className={input} defaultValue="2026-12-31" required type="date" /></Label><Label title="Goal colour"><select className={select}><option>Indigo</option><option>Green</option><option>Pink</option><option>Amber</option></select></Label></>
  return <><div className="rounded-lg bg-muted p-4 text-sm"><p className="text-muted-foreground">Add a one-time contribution to this goal.</p><p className="mt-1 text-xl font-semibold">Every amount counts</p></div><Label title="Contribution amount"><input autoFocus className={input} min="1" placeholder="0" required type="number" /></Label><Label title="Note (optional)"><input className={input} placeholder="e.g. July savings" /></Label></>
}
function Success({ kind }: { kind: FinanceDialogKind }) { return <div className="grid min-h-44 place-items-center text-center"><div><span className="mx-auto grid size-11 place-items-center rounded-full bg-success-soft text-success"><Check className="size-5" /></span><h3 className="mt-3 text-sm font-semibold">Ready to continue</h3><p className="mt-1 text-xs text-muted-foreground">Your {kind === 'import' ? 'file is ready for validation' : kind === 'export' ? 'export has been prepared' : 'changes have been saved'}.</p></div></div> }

export function ConfirmDialog({ title, description, onClose }: { title: string; description: string; onClose: () => void }) { const [done, setDone] = useState(false); return <div aria-modal="true" className="fixed inset-0 z-70 grid place-items-center bg-foreground/40 p-4" role="dialog"><section className="w-full max-w-sm rounded-xl border border-border bg-card shadow-xl"><div className="p-5">{done ? <Success kind="goal" /> : <><h2 className="font-semibold">{title}</h2><p className="mt-2 text-sm text-muted-foreground">{description}</p></>}</div><footer className="flex justify-end gap-2 border-t border-border bg-muted/25 px-5 py-4">{done ? <button className={buttonVariants()} onClick={onClose} type="button">Done</button> : <><button className={buttonVariants({ variant: 'ghost' })} onClick={onClose} type="button">Cancel</button><button className={buttonVariants({ variant: 'destructive' })} onClick={() => setDone(true)} type="button">Delete</button></>}</footer></section></div> }

export function RowMenu({ kind }: { kind: 'transaction' | 'budget' | 'goal' }) { const [dialog, setDialog] = useState<'edit' | 'delete' | null>(null); return <><details className="relative"><summary aria-label="More actions" className="grid size-7 cursor-pointer list-none place-items-center rounded-md text-muted-foreground hover:bg-muted hover:text-foreground [&::-webkit-details-marker]:hidden"><Ellipsis className="size-4" /></summary><div className="absolute right-0 top-8 z-20 w-28 rounded-lg border border-border bg-card p-1 shadow-md"><button className="flex w-full items-center rounded-md px-2.5 py-2 text-left text-xs font-medium text-muted-foreground hover:bg-muted hover:text-foreground" onClick={() => setDialog('edit')} type="button"><Pencil className="mr-2 size-3" />Edit</button><button className="flex w-full items-center rounded-md px-2.5 py-2 text-left text-xs font-medium text-danger hover:bg-danger-soft" onClick={() => setDialog('delete')} type="button"><Trash2 className="mr-2 size-3" />Delete</button></div></details>{dialog === 'edit' ? <FinanceDialog editing kind={kind} onClose={() => setDialog(null)} /> : null}{dialog === 'delete' ? <ConfirmDialog description="This action cannot be undone. Related information will remain available where required." onClose={() => setDialog(null)} title={`Delete ${kind}`} /> : null}</> }
